source 'http://rubygems.org'

gem 'log4r', '~> 1.1.10'
gem 'awesome_print', '~> 1.2.0'
gem 'term-ansicolor', '~> 1.3.0'
gem 'pry', '~> 0.9.0'
gem 'pry-debugger', '~> 0.2.2'
gem 'pry-rails', '~> 0.3.2'
gem 'pry-stack_explorer', '~> 0.4.9.1'

